import { DrumPattern } from './DrumMachineContext'

export const DEFAULT_PATTERNS: DrumPattern[] = [
  {
    name: 'Rock Basic',
    bpm: 120,
    volumes: { kick: 85, snare: 80, hihat: 45, openhat: 65, crash: 70, ride: 60, tom1: 75, tom2: 75 },
    steps: [
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Funk',
    bpm: 105,
    volumes: { kick: 80, snare: 85, hihat: 55, openhat: 60, crash: 60, ride: 55, tom1: 70, tom2: 70 },
    steps: [
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Metal',
    bpm: 155,
    volumes: { kick: 90, snare: 85, hihat: 55, openhat: 65, crash: 75, ride: 65, tom1: 80, tom2: 80 },
    steps: [
      { kick: true, snare: false, hihat: false, openhat: false, crash: true, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: true, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: true, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Jazz Swing',
    bpm: 140,
    volumes: { kick: 70, snare: 75, hihat: 55, openhat: 50, crash: 60, ride: 60, tom1: 65, tom2: 65 },
    steps: [
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Hip-Hop',
    bpm: 92,
    volumes: { kick: 85, snare: 80, hihat: 65, openhat: 60, crash: 55, ride: 55, tom1: 70, tom2: 70 },
    steps: [
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Reggae',
    bpm: 78,
    volumes: { kick: 75, snare: 70, hihat: 65, openhat: 60, crash: 60, ride: 55, tom1: 65, tom2: 65 },
    steps: [
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Disco',
    bpm: 124,
    volumes: { kick: 88, snare: 82, hihat: 65, openhat: 70, crash: 70, ride: 65, tom1: 78, tom2: 78 },
    steps: [
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Latin',
    bpm: 112,
    volumes: { kick: 80, snare: 78, hihat: 68, openhat: 65, crash: 65, ride: 53, tom1: 72, tom2: 72 },
    steps: [
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: true, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Breakbeat',
    bpm: 128,
    volumes: { kick: 88, snare: 84, hihat: 70, openhat: 68, crash: 68, ride: 62, tom1: 78, tom2: 78 },
    steps: [
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Shuffle',
    bpm: 116,
    volumes: { kick: 82, snare: 78, hihat: 68, openhat: 65, crash: 65, ride: 60, tom1: 72, tom2: 72 },
    steps: [
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: true, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  },
  {
    name: 'Minimal',
    bpm: 90,
    volumes: { kick: 78, snare: 74, hihat: 60, openhat: 58, crash: 55, ride: 55, tom1: 65, tom2: 65 },
    steps: [
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: true, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: true, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false },
      { kick: false, snare: false, hihat: false, openhat: false, crash: false, ride: false, tom1: false, tom2: false }
    ]
  }
]
